version: '2'
services:
  db:
    image: postgres:9.5.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: casebook_api_development
  api:
    build: .
    command: ./bin/docker_start
    environment:
      PG_HOST: db
      PG_USER: postgres
    volumes:
      - .:/casebook_api
      - casebook_api_rubygems:/ruby_gems

