version: '2'
services:
  db:
    extends:
      file: ./docker-compose.common.yml
      service: db
  api:
    extends:
      file: ./docker-compose.common.yml
      service: api
    links:
      - db
    ports:
      - "3001:3000"
volumes:
  casebook_api_rubygems:

