swagger: '2.0'
info:
  version: '1'
  title: Casebook Mock API
  description: Mock API used for development of Accelerator and California Intake project

host: 192.168.99.103:3001
basePath: /api/v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
definitions:
  Participant:
    type: object
    properties:
      person_id:
        type: string
      screening_id:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      gender:
        type: string
        enum:
          - male
          - female
      date_of_birth:
        type: string
        format: date
      ssn:
        type: string
      addresses:
        type: array
        items:
          $ref: '#/definitions/Address'
      phone_numbers:
        type: array
        items:
          $ref: '#/definitions/PhoneNumber'
      roles:
        type: array
        items:
          type: string
          enum:
            - Anonymous Reporter
            - Mandated Reporter
            - Non-mandated Reporter
            - Perpetrator
            - Victim
    required:
      - screening_id
  Person:
    type: object
    properties:
      first_name:
        type: string
      middle_name:
        type: string
      last_name:
        type: string
      name_suffix:
        type: string
        enum:
          - esq
          - ii
          - iii
          - iv
          - jr
          - sr
          - md
          - phd
          - jd
      gender:
        type: string
        enum:
          - male
          - female
      date_of_birth:
        type: string
        format: date
      ssn:
        type: string
      languages:
        type: array
        items:
          type: string
          enum:
            - American Sign Language
            - Arabic
            - Armenian
            - Cambodian
            - Cantonese
            - English
            - Farsi
            - Filipino
            - French
            - German
            - Hawaiian
            - Hebrew
            - Hmong
            - Ilacano
            - Indochinese
            - Italian
            - Japanese
            - Korean
            - Lao
            - Mandarin
            - Mien
            - Other Chinese
            - Other Non-English
            - Polish
            - Portuguese
            - Romanian
            - Russian
            - Samoan
            - Sign Language (Not ASL)
            - Spanish
            - Tagalog
            - Thai
            - Turkish
            - Vietnamese
      races:
        type: array
        items:
          type: object
          properties:
            race:
              type: string
              enum:
                - White
                - Black or African American
                - Asian
                - American Indian or Alaskan Native
                - Native Hawaiian or Other Pacific Islander
                - Unknown
                - Abandoned
                - Declined to answer
            race_detail:
              type: string
              enum:
                - Armenian
                - Central American
                - European
                - Middle Eastern
                - Romanian
                - Black
                - Ethiopian
                - Caribbean
                - Asian Indian
                - Cambodian
                - Chinese
                - Filipino
                - Hmong
                - Japanese
                - Korean
                - Laotian
                - Other Asian
                - Vietnamese
                - American Indian
                - Alaskan Native
                - Guamanian
                - Hawaiian
                - Other Asian/Pacific Islander
                - Other Pacific Islander
                - Polynesian
                - Samoan
      ethnicity:
        type: object
        properties:
          hispanic_latino_origin:
            type: string
            enum:
              - Yes
              - No
              - Unknown
              - Abandoned
              - Declined to answer
          ethnicity_detail:
            type: string
            enum:
              - Hispanic
              - Mexican
              - Central American
              - South American
      addresses:
        type: array
        items:
          $ref: '#/definitions/Address'
      phone_numbers:
        type: array
        items:
          $ref: '#/definitions/PhoneNumber'
  ParticipantResponse:
    allOf:
      - $ref: "#/definitions/Participant"
      - type: object
        properties:
          id:
            type: string
  PersonResponse:
    type: object
    allOf:
      - $ref: "#/definitions/Person"
      - type: object
        properties:
          id:
            type: string
        required:
          - id
  Address:
    type: object
    properties:
      id:
        type: string
      street_address:
        type: string
      city:
        type: string
      state:
        type: string
      zip:
        type: string
      type:
        type: string
        enum:
          - Home
          - School
          - Work
          - Placement
          - Homeless
          - Other
  Allegation:
    type: object
    required:
      - allegation_types
    properties:
      allegation_types:
        type: array
        items:
          type: string
        enum:
          - General neglect
          - Severe neglect
          - Physical abuse
          - Sexual abuse
          - Emotional abuse
          - Caretaker absent/incapacity
          - Exploitation
          - Sibling at risk
      victim_id:
        type: string
      perpetrator_id:
        type: string
  PhoneNumber:
    type: object
    properties:
      id:
        type: string
      number:
        type: string
      type:
        type: string
        enum:
          - Cell
          - Work
          - Home
          - Other
  CrossReport:
    type: object
    properties:
      agency_type:
        type: string
        enum:
          - District attorney
          - Law enforcement
          - Department of justice
          - Licensing
      agency_name:
        type: string
        maxLength: 128
  Screening:
    type: object
    properties:
      reference:
        type: string
      additional_information:
        type: string
      ended_at:
        type: string
        format: date-time
      incident_county:
        type: string
      incident_date:
        type: string
        format: date
      location_type:
        type: string
      communication_method:
        type: string
      name:
        type: string
      screening_decision_detail:
        type: string
      screening_decision:
        type: string
      started_at:
        type: string
        format: date-time
      report_narrative:
        type: string
      cross_reports:
        type: array
        items:
          $ref: '#/definitions/CrossReport'
      address:
        $ref: '#/definitions/Address'
      assignee:
        type: string
      allegations:
        type: array
        items:
          $ref: '#/definitions/Allegation'
  ScreeningResponse:
    allOf:
      - $ref: '#/definitions/Screening'
      - type: object
        properties:
          id:
            type: string
          participants:
            type: array
            items:
              $ref: '#/definitions/ParticipantResponse'

parameters:
  AuthorizationHeader:
    name: Authorization
    in: header
    type: string
    required: true
    description: Authorization token

paths:
  /people/{id}:
    get:
      description: Gets `Person` object for the id.
      tags:
        - people
        - person
      parameters:
        - $ref: '#/parameters/AuthorizationHeader'
        - name: id
          in: path
          description: id of the person
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/PersonResponse'
    put:
      description: Updates a `Person` object.
      tags:
        - people
        - person
      parameters:
        - $ref: '#/parameters/AuthorizationHeader'
        - name: id
          in: path
          description: id of the person
          required: true
          type: string
        - name: body
          in: body
          description: Person to update
          required: true
          schema:
            $ref: '#/definitions/Person'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/PersonResponse'

  /people:
    post:
      summary: Creates a `Person` object.
      operationId: createPerson
      parameters:
        - $ref: '#/parameters/AuthorizationHeader'
        - name: body
          in: body
          description: Person to create
          required: true
          schema:
            $ref: '#/definitions/Person'
      responses:
        201:
          description: Successful creation
          schema:
            $ref: '#/definitions/PersonResponse'

  /people_search:
    get:
      summary: Gets People by searching the provided search_term
      description: Gets `People` by searching the provided search_term.
      tags:
        - people
      operationId: peopleSearch
      parameters:
        - $ref: '#/parameters/AuthorizationHeader'
        - name: search_term
          in: query
          description: the search term to search
          required: true
          type: string
      responses:
        200:
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/PersonResponse'

  /screenings/{id}:
    get:
      description: Gets `Screening` object for the id.
      tags:
        - screenings
        - screening
      parameters:
        - $ref: '#/parameters/AuthorizationHeader'
        - name: id
          in: path
          description: id of the screening
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/ScreeningResponse'
    put:
      description: Updates a `Screening` object
      tags:
        - screenings
        - screening
      parameters:
        - $ref: '#/parameters/AuthorizationHeader'
        - name: id
          in: path
          description: id of the screening
          required: true
          type: string
        - name: body
          in: body
          description: Screening parameters
          required: true
          schema:
            $ref: '#/definitions/Screening'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/ScreeningResponse'
  
  /screenings/{id}/history_of_involvements:
    get:
      description: Gets related `Screening` objects for the screening.
      tags:
        - screenings
        - screening
      parameters:
        - $ref: '#/parameters/AuthorizationHeader'
        - name: id
          in: path
          description: id of the screening
          required: true
          type: string
      responses:
        200:
          description: Successful response
          type: array
          items:
              $ref: '#/definitions/ScreeningResponse'

  /screenings:
    post:
      description: Creates a new screening
      tags:
        - screenings
        - screening
      parameters:
        - $ref: '#/parameters/AuthorizationHeader'
        - name: body
          in: body
          description: Screening parameters
          required: true
          schema:
            $ref: '#/definitions/Screening'
      responses:
        200:
          description: Successful creation
          schema:
            $ref: '#/definitions/ScreeningResponse'
            
    get:
      summary: Gets Screenings by response times and or screening decision 
      description: Gets `Screenings` by response times and or screening decision.
      tags:
        - screenings
      parameters:
        - $ref: '#/parameters/AuthorizationHeader'
        - name: screening_decision_details
          in: query
          description: the expected screening_decision_details of listed screenings
          type: array
          items:
            type: string
            enum:
              - immediate
              - 3_days
              - 5_days
              - 10_days
        - name: screening_decisions
          in: query
          description: the expected screening_decision of listed screenings
          type: array
          items:
            type: string
            enum:
              - differential_response
              - information_to_child_welfare_services
              - promote_to_referral
              - screen_out
      responses:
        200:
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/ScreeningResponse'

  /participants/{id}:
    delete:
      summary: Deletes a `Participant` Object
      operationId: deleteParticipant
      parameters:
        - $ref: '#/parameters/AuthorizationHeader'
        - name: id
          in: path
          description: Participant id to delete
          required: true
          type: string
      responses:
        204:
          description: Successful deletion
    put:
      description: Updates a `Participant` object
      tags:
        - participant
        - participants
      parameters:
        - $ref: '#/parameters/AuthorizationHeader'
        - name: id
          in: path
          description: id of the participant
          required: true
          type: string
        - name: body
          in: body
          description: participant parameters
          required: true
          schema:
            $ref: '#/definitions/Participant'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/ParticipantResponse'

  /participants:
    post:
      summary: Creates a `Participant` object.
      operationId: createParticipant
      parameters:
        - $ref: '#/parameters/AuthorizationHeader'
        - name: body
          in: body
          description: Participant to create
          required: true
          schema:
            $ref: '#/definitions/Participant'
      responses:
        201:
          description: Successful creation
          schema:
            $ref: '#/definitions/ParticipantResponse'
