default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch('PG_HOST', 'localhost') %>
  port: <%= ENV.fetch('PG_PORT', 5432) %>
  username: <%= ENV.fetch('PG_USER', 'casebook') %>
  password: <%= ENV.fetch('PG_PASSWORD', '') %>

development:
  <<: *default
  database: casebook_api_development

test:
  <<: *default
  database: casebook_api_test

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'casebook_api_production') %>
